baseurl: /leerKRACHT
permalink: pretty
markdown: rdiscount
prose:
  rooturl: '/leerKRACHT'
  siteurl: 'http://prose.github.io/leerKRACHT/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
 
